name: deploy website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ngduc/vercel-deploy-action@master
        with:
         
          vercel-token:  ${{ secrets.VERCEL_TOKEN }} # Required
         
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    
        
      
          working-directory: ./sub-directory
