name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Installing my packages
      run: npm ci

    - name: Build my App  
      run: npm run build
      env:
        NEXT_PUBLIC_BASE_PATH: /social-media-app
        NEXT_PUBLIC_GOOGLE_CLIENT_ID : 511520526419-situbspaa4tcaks3qbcotmf5qvt4gb35.apps.googleusercontent.com
        NEXT_PUBLIC_GOOGLE_CLIENT_SECRET : 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
        NEXT_PUBLIC_NEXTAUTH_URL : https://github.com/TarikPasalic7/social-media-app
    - run: npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: /social-media-app
        NEXT_PUBLIC_GOOGLE_CLIENT_ID : 511520526419-situbspaa4tcaks3qbcotmf5qvt4gb35.apps.googleusercontent.com
        NEXT_PUBLIC_GOOGLE_CLIENT_SECRET : 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
        NEXT_PUBLIC_NEXTAUTH_URL : https://github.com/TarikPasalic7/social-media-app
    - run: touch ./out/.nojekyll
    
 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
